use master;

CREATE TABLE RAW_MOCKDATA (
    BATCH_ID INTEGER NOT NULL,
    ENTITY_ID INTEGER NOT NULL,
    ENTITY_TYPE VARCHAR(30) NOT NULL
);


CREATE TABLE STG_MOCKDATA(
	BATCH_ID INTEGER NOT NULL,
    ENTITY_ID INTEGER NOT NULL,
    ENTITY_TYPE VARCHAR(30) NOT NULL
);

CREATE TABLE MAPPING_OVERVIEW(
    ENTITY_TYPE VARCHAR(30),
    SOURCE_OBJECT VARCHAR(50),
    SOURCE_RECORD_COUNT INTEGER,
    TARGET_OBJECT VARCHAR(50),
    TARGET_RECORD_COUNT INTEGER,
    IS_MATCHED VARCHAR(10),
    COUNT_DIFFERENCE INTEGER
)

CREATE TABLE MAPPING_DETAIL(
    AUDIT_ID INTEGER IDENTITY(1,1),
    LOAD_PHASE VARCHAR(20),
    BATCH_ID INTEGER,
    ENTITY_ID INTEGER,
    SOURCE_OBJECT VARCHAR(50),
    SOURCE_COLUMN VARCHAR(50),
    SOURCE_VALUE VARCHAR(50),
    TARGET_OBJECT VARCHAR(50),
    TARGET_COLUMN VARCHAR(50),
    TARGET_VALUE VARCHAR(50),
    AUDIT_RESULT VARCHAR(20)
)

-- First clear both tables (if needed)
TRUNCATE TABLE STG_MOCKDATA;
TRUNCATE TABLE RAW_MOCKDATA;

-- Insert into RAW_MOCKDATA (>100 rows, 4 types)
DECLARE @i INT = 1;

WHILE @i <= 120
BEGIN
    INSERT INTO RAW_MOCKDATA (BATCH_ID, ENTITY_ID, ENTITY_TYPE)
    VALUES
    (
        CEILING(RAND() * 5),                          -- Random Batch_ID between 1 and 5
        @i,                                           -- Unique ENTITY_ID
        CASE                                           
            WHEN @i <= 30 THEN 'Customer'             -- 30 Customers
            WHEN @i <= 60 THEN 'Supplier'             -- 30 Suppliers
            WHEN @i <= 90 THEN 'Product'              -- 30 Products
            ELSE 'Order'                              -- 30 Orders
        END
    );

    SET @i = @i + 1;
END

-- Insert full Customer data (all 30) into STG
INSERT INTO STG_MOCKDATA (BATCH_ID, ENTITY_ID, ENTITY_TYPE)
SELECT BATCH_ID, ENTITY_ID, ENTITY_TYPE
FROM RAW_MOCKDATA
WHERE ENTITY_TYPE = 'Customer';

-- Insert full Product data (all 30) into STG
INSERT INTO STG_MOCKDATA (BATCH_ID, ENTITY_ID, ENTITY_TYPE)
SELECT BATCH_ID, ENTITY_ID, ENTITY_TYPE
FROM RAW_MOCKDATA
WHERE ENTITY_TYPE = 'Product';

-- Insert partial Supplier data (e.g., 10 out of 30)
INSERT INTO STG_MOCKDATA (BATCH_ID, ENTITY_ID, ENTITY_TYPE)
SELECT TOP 10 BATCH_ID, ENTITY_ID, ENTITY_TYPE
FROM RAW_MOCKDATA
WHERE ENTITY_TYPE = 'Supplier'
ORDER BY NEWID();

-- Insert partial Order data (e.g., 5 out of 30)
INSERT INTO STG_MOCKDATA (BATCH_ID, ENTITY_ID, ENTITY_TYPE)
SELECT TOP 5 BATCH_ID, ENTITY_ID, ENTITY_TYPE
FROM RAW_MOCKDATA
WHERE ENTITY_TYPE = 'Order'
ORDER BY NEWID();

SELECT ENTITY_TYPE, COUNT(*) AS TotalCount
FROM RAW_MOCKDATA
GROUP BY ENTITY_TYPE;

SELECT ENTITY_TYPE, COUNT(*) AS TotalCount
FROM STG_MOCKDATA
GROUP BY ENTITY_TYPE;

SELECT * FROM RAW_MOCKDATA;

SELECT * FROM STG_MOCKDATA;

SELECT * FROM MAPPING_OVERVIEW;

SELECT * FROM MAPPING_DETAIL ORDER BY BATCH_ID, ENTITY_ID, SOURCE_OBJECT, SOURCE_COLUMN;

--TRUNCATE TABLE MAPPING_DETAIL;
