IF OBJECT_ID('dbo.INSERT_OVERVIEW_MOCK', 'P') IS NOT NULL
    DROP PROCEDURE dbo.INSERT_OVERVIEW_MOCK;
GO

CREATE PROCEDURE dbo.INSERT_OVERVIEW_MOCK
AS
BEGIN
    INSERT INTO dbo.MAPPING_DETAIL (ENTITY_TYPE, SOURCE_OBJECT, SOURCE_RECORD_COUNT, TARGET_OBJECT, TARGET_RECORD_COUNT, IS_MATCHED, COUNT_DIFFERENCE)
    SELECT 
        RAW_TABLE.ENTITY_TYPE,
        'RAW_MOCKDATA',
        RAW_TABLE.TOTAL_RECORDS,
        'STG_MOCKDATA',
        STG_TABLE.TOTAL_RECORDS,
        CASE
            WHEN RAW_TABLE.TOTAL_RECORDS = STG_TABLE.TOTAL_RECORDS
            THEN 'Match'
            ELSE 'Not Match'
        END AS IS_MATCHED,
        ABS(RAW_TABLE.TOTAL_RECORDS - STG_TABLE.TOTAL_RECORDS) AS COUNT_DIFFERENCE
    FROM
        (SELECT ENTITY_TYPE, COUNT(*) AS TOTAL_RECORDS
        FROM dbo.RAW_MOCKDATA
        GROUP BY ENTITY_TYPE) RAW_TABLE
        LEFT OUTER JOIN 
        (SELECT ENTITY_TYPE, COUNT(*) AS TOTAL_RECORDS
        FROM dbo.STG_MOCKDATA
        GROUP BY ENTITY_TYPE) STG_TABLE
        ON RAW_TABLE.ENTITY_TYPE = STG_TABLE.ENTITY_TYPE;
END;

EXEC INSERT_OVERVIEW_MOCK;